# Generated by Django 4.0.1 on 2023-10-11 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prod_Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_no', models.CharField(max_length=15)),
                ('plan_0day', models.IntegerField()),
                ('plan_1day', models.IntegerField()),
                ('plan_2day', models.IntegerField()),
                ('plan_3day', models.IntegerField()),
                ('plan_4day', models.IntegerField()),
                ('plan_5day', models.IntegerField()),
                ('plan_6day', models.IntegerField()),
                ('plan_7day', models.IntegerField()),
                ('plan_8day', models.IntegerField()),
                ('plan_9day', models.IntegerField()),
                ('plan_date', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'prod_plan',
                'managed': False,
            },
        ),
    ]
